# Application Name
spring.application.name=Digital Timetable System

# Server Port
server.port=8091

# ==================== Database Configuration (MySQL) ====================
spring.datasource.url=jdbc:mysql://${DATABASE_HOST:turntable.proxy.rlwy.net}:${DATABASE_PORT:28825}/${DATABASE_NAME:railway}
spring.datasource.username=${DATABASE_USER:root}
spring.datasource.password=${DATABASE_PASSWORD:RmthnXupuvYQOVKMUTAYwOSlmTkyMewF}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Allow circular references temporarily
spring.main.allow-circular-references=true

# JWT Secret Key
secreteJwtString=QAU21yVhYKc9wFH701SZB62ZYiVoBsjQBMJDrGyCkItpS2EhO5rePOsKX7t6QUtYbSpItocaBQK9Di45ThVqM8u

# WebSocket Configuration
spring.websocket.max-text-message-size=64KB
spring.websocket.max-binary-message-size=64KB

# Logging Configuration
logging.level.com.bank.Banking=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.messaging=DEBUG

# Server Configuration
server.tomcat.max-threads=200
server.tomcat.min-spare-threads=10
server.tomcat.max-connections=8192
server.tomcat.accept-count=100

# ===== Mail Configuration =====
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=alainvalentin04@gmail.com
spring.mail.password=aivjvmuibcgvlmmk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.default-encoding=UTF-8

# Toggle email sending (true to enable, false to skip sending)
app.mail.enabled=true

# Default From address with display name
app.mail.from=alainvalentin04@gmail.com
